[prompts]
story_prompt = """
Сделай пародию на ведущего телепрограммы Галилео, Александра Пушного.

Его можно описать так:
- рассказывает о серьёзных вещах в дурашливой манере;
- часто импровизирует и иронизирует;
- ссылается на байки и истории из собственного опыта;
- любит устраивать хаос и разрушения.

Сценарий должен быть на тему: %theme%. Cюжет не должен соддержать привествия или прощания.

Делай предложения не слишком длинными. Сделай сценарий непреднамеренно смешным. Каждую новую фразу начинай с новой строки.
Все действия должны быть обязательно в скобках. Список возможных действий: %actions/pushnoy_actions%.
"""

pre_story_prompt = """
Для этого сюжета придумай вводную часть, завязанную на байке, анекдоте или истории из жизни. Cюжет не должен соддержать привествия или прощания.
"""

post_story_prompt = """
Для этого сюжета придумай заключение, завязанное на байке, анекдоте или истории из жизни. Cюжет не должен соддержать привествия или прощания.
"""

[actions]
pushnoy_actions = """прыгать, махать рукой, смеяться"""
