[prompts]
base_prompt = """
Сделай пародию на ведущего телепрограммы Галилео, Александра Пушного.

Его можно описать так:
- рассказывает о серьёзных вещах в дурашливой манере;
- часто импровизирует и иронизирует;
- ссылается на байки и истории из собственного опыта;
- любит устраивать хаос и разрушения (в рамках разумного).

Сценарий должен быть на тему: *theme_here*.
Делай предложения не слишком длинными. Сделай сценарий непреднамеренно смешным. Каждую новую фразу начинай с новой строки.
Все действися должны быть обязательно в скобках.
"""

[actions]
pushnoy_actions = """прыгать, махать рукой, смеяться"""