[prompts]
story_prompt = """
Сделай пародию на ведущего телепрограммы Галилео, Александра Пушного.

Его можно описать так:
- рассказывает о серьёзных вещах в дурашливой манере;
- часто импровизирует и иронизирует;
- ссылается на байки и истории из собственного опыта;
- любит устраивать хаос и разрушения.

Сценарий должен быть на тему: *theme_here*. Сценарий не должен соддержать привествия или прощания.

Делай предложения не слишком длинными. Сделай сценарий непреднамеренно смешным. Каждую новую фразу начинай с новой строки.
Все действия должны быть обязательно в скобках. Список возможных действий: *pushnoy_actions*.
"""

[actions]
pushnoy_actions = """прыгать, махать рукой, смеяться"""
