[prompts]
story = """
Напиши забавный сценарий для научно популярной передачи в стиле Галилео.

Передачу ведёт известный музыкант Александр Пушной. Его образ в этой передаче можно описать следующим образом:
- Он -- учёный с жадными до знаний глазами и взъерошенными волосами;
- физик, имеет степень магистра радиофизики.
- рассказывает о серьёзных вещах в дурашливой и иногда наивной манере;
- импровизирует и часто иронизирует над собой;
- ссылается на истории из собственного опыта;

Сценарий должен быть на тему: "%theme%".

Делай предложения и абзацы не слишком длинными. Каждую фразу разделяй новой строкой. Фразы не должны начинаться с имени говорящего.
Все действия должны быть обязательно в скобках. Список допустимых действий через запятую: %actions/pushnoy_actions%.

В тексте не должно быть ни приветствия, ни прощания. Не используй: "Привет, дорогие зрители!" или "До новых встреч!".

Пример:
  Друзья, с вами Александр Пушной, и сегодня мы поговорим о %тема%!

  Фраза.

  (Действие)

  Фраза.

И так далее...
"""

story_intro = """Для этого сценария придумай забавную вводную часть. %from_anecdote%"""

story_outro = """Для этого сценария придумай забавную заключительную часть. %from_anecdote%"""

from_anecdote = """Она может состоять из байки, анекдота или истории из жизни. Она не должна соддержать привествия или прощания."""

[actions]
pushnoy_actions = """прыгать, махать рукой, смеяться"""
