[prompts]
story = """
Сделай пародию на ведущего телепрограммы Галилео, Александра Пушного.

Его персонажа можно описать так:
- рассказывает о серьёзных вещах в дурашливой манере;
- часто импровизирует и иронизирует;
- ссылается на байки и истории из собственного опыта;
- любит устраивать хаос и разрушения;
- эдакий безумный учёный с жадными до знаний глазами и взъерошенными волосами;
- физик, имеет степень магистра радиофизики.

Сценарий должен быть на тему: %theme%.

Делай предложения не слишком длинными. Сделай сценарий непреднамеренно смешным. Каждую новую фразу начинай с новой строки.
Все действия должны быть обязательно в скобках. Список возможных действий: %actions/pushnoy_actions%.
"""

story_new = """
Напиши юмористический сценарий для научно популярной передачи в стиле Галилео.

Передачу ведёт известный музыкант Александр Пушной. Его образ в этой передаче можно описать следующим образом:
- Он -- учёный с жадными до знаний глазами и взъерошенными волосами;
- физик, имеет степень магистра радиофизики.
- рассказывает о серьёзных вещах в дурашливой и иногда наивной манере;
- импровизирует и часто иронизирует над собой;
- ссылается на истории из собственного опыта;

Сценарий должен быть на тему: "%theme%".

Делай предложения и абзацы короткими. Фразы разделяй новой строкой. В тексте не должно быть ничего, кроме фраз.
Все действия должны быть обязательно в скобках. Список допустимых действий: %actions/pushnoy_actions%.

Не добавляй обращение к зрителям в начале или в конце сюжета.

Пример:
  Текст 1.

  Текст 2.

  (Смеяться)

  Текст 3.

  И так далее...
"""

story_intro = """Для этого сюжета придумай вводную часть. %from_anecdote%"""

story_outro = """Для этого сюжета придумай заключительную часть. %from_anecdote%"""

from_anecdote = """Она может состоять из байки, анекдота или истории из жизни. Она не должна соддержать привествия или прощания."""

[actions]
pushnoy_actions = """прыгать, махать рукой, смеяться"""
