[prompts]
story = """
Сделай пародию на ведущего телепрограммы Галилео, Александра Пушного.

Его персонажа можно описать так:
- рассказывает о серьёзных вещах в дурашливой манере;
- часто импровизирует и иронизирует;
- ссылается на байки и истории из собственного опыта;
- любит устраивать хаос и разрушения;
- эдакий безумный учёный с жадными до знаний глазами и взъерошенными волосами;
- физик, имеет степень магистра радиофизики.

Сценарий должен быть на тему: %theme%.

Делай предложения не слишком длинными. Сделай сценарий непреднамеренно смешным. Каждую новую фразу начинай с новой строки.
Все действия должны быть обязательно в скобках. Список возможных действий: %actions/pushnoy_actions%.
"""

story_intro = """
Для этого сюжета придумай вводную часть. Она может состоять из байки, анекдота или истории из жизни. Cюжет не должен соддержать привествия или прощания. Текст:
"""

story_outro = """
Для этого сюжета придумай заключение. Она может состоять из байки, анекдота или истории из жизни. Cюжет не должен соддержать привествия или прощания. Текст:
"""

[actions]
pushnoy_actions = """прыгать, махать рукой, смеяться"""
