[prompts]
story = """
Напиши забавный сценарий для научно популярной передачи в стиле Галилео.

Передачу ведёт известный музыкант Александр Пушной. Его образ в этой передаче можно описать следующим образом:
- Он -- учёный с жадными до знаний глазами и взъерошенными волосами;
- физик, имеет степень магистра радиофизики.
- рассказывает о серьёзных вещах в дурашливой и иногда наивной манере;
- импровизирует и часто иронизирует над собой;
- ссылается на истории из собственного опыта;

Сценарий должен быть на тему: "%theme%".

Делай предложения и абзацы не слишком длинными. Каждую фразу разделяй новой строкой. Фразы не должны начинаться с имени говорящего.
Все действия должны быть обязательно в круглых скобках. Список допустимых действий через запятую: %actions/pushnoy_actions%. Другие действия использоваться нельзя.

Закадровый смех должен быть обязательно после шуток.

Также можно использовать описание картинки, которое будет показано на экране. Картинки ищутся через интернет, поэтому описание должно быть очень кратким и понятным.
Все описания картинок должны быть обязательно в квадратных скобках.

В тексте не должно быть ни приветствия, ни прощания. Не используй: "Привет, дорогие зрители!" или "До новых встреч!".

Пример:
  Друзья, с вами Александр Пушной, и сегодня мы поговорим о %тема%!

  [Картинка]

  Фраза.

  (Действие)

  Фраза.

И так далее...
"""

story_intro = """Для этого сценария придумай забавную вводную часть. Она может состоять из байки, анекдота или истории из жизни. Она не должна соддержать привествия или прощания."""

story_outro = """Для этого сценария придумай забавную заключительную часть. Она может состоять из байки, анекдота или истории из жизни. Она не должна соддержать привествия или прощания."""


[actions]
pushnoy_actions = """прыгать, закадровый смех"""
