[prompts]
story = """
Сделай пародию на ведущего телепрограммы Галилео, Александра Пушного.

Его можно описать так:
- рассказывает о серьёзных вещах в дурашливой манере;
- часто импровизирует и иронизирует;
- ссылается на байки и истории из собственного опыта;
- любит устраивать хаос и разрушения;
- эдакий безумный учёный с жадными до знаний глазами и взъерошенными волосами;
- выучился на физик, имеет степень магистра радиофизики.

Сценарий должен быть на тему: %theme%.

Делай предложения не слишком длинными. Сделай сценарий непреднамеренно смешным. Каждую новую фразу начинай с новой строки.
Все действия должны быть обязательно в скобках. Список возможных действий: %actions/pushnoy_actions%.
"""

pre_story = """
Для этого сюжета придумай вводную часть, завязанную на байке, анекдоте или истории из жизни. Cюжет не должен соддержать привествия или прощания.
"""

post_story = """
Для этого сюжета придумай заключение, завязанное на байке, анекдоте или истории из жизни. Cюжет не должен соддержать привествия или прощания.
"""

[actions]
pushnoy_actions = """прыгать, махать рукой, смеяться"""
